---
- name: Install required software
  ansible.builtin.package:
    name: unzip
    state: present

- name: Set download directory if install only for the user
  ansible.builtin.set_fact:
    k0s_runtime_dir: "{{ ansible_user_dir }}/bin"
  when: not k0s_for_all_users | bool

- name: Set download directory for all users to use
  ansible.builtin.set_fact:
    k0s_runtime_dir: "/usr/local/bin"
  when: k0s_for_all_users | bool

- name: Create bin directory in users home if necessary for local install
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/bin"
    state: directory
    mode: 0755
  when: not k0s_for_all_users | bool

- name: Download file
  ansible.builtin.get_url:
    url: "https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-amd64"
    dest: "/tmp/k0s"
    mode: 0755

- name: Copy file to runtime directory
  ansible.builtin.copy:
    src: "/tmp/k0s"
    dest: "{{ k0s_runtime_dir }}"
    mode: 0755
    remote_src: yes
