---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    k0s_for_all_users: true
    command_shell: bash
  tasks:
    - name: Set download directory if install only for the user
      set_fact:
        k0s_runtime_dir: "{{ ansible_user_dir }}/bin"
      when: not k0s_for_all_users | bool

    - name: Set download directory for all users to use
      set_fact:
        k0s_runtime_dir: "/usr/local/bin"
      when: k0s_for_all_users | bool

    - name: Find the k0s file
      ansible.builtin.stat:
        path: "{{ k0s_runtime_dir }}/k0s"
      register: k0s_file

    - name: Print stat info
      debug:
        msg: "{{ k0s_file.stat }}"

    - name: Assert that k0s exists
      assert:
        that: k0s_file.stat.exists

    - name: Assert that k0s is executable
      assert:
        that: k0s_file.stat.executable
